ci:
    autoupdate_schedule: 'weekly'
    autofix_prs: true

repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: trailing-whitespace
